stages:
  - analyze # linting, testing (with coverage), static code analysis, and upload to sonarqube

variables:
  profiles: "ui,loader,memory"

build:
  only:
    refs:
      - master
  stage: analyze
  image: openjdk:11-jdk
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "/root/.ivy2/cache"
      - "/root/.sbt"
      - "/root/.m2"
      - "/root/.elm"
  before_script:
    - ./ci-scripts/install-isabelle.sh
    - echo 'ISABELLE_TOOL_JAVA_OPTIONS="-Xms1600m -Xmx1600m"' >> /root/.isabelle/etc/settings
    - echo 'ML_OPTIONS="--minheap 1800M --maxheap 1800M"' >> /root/.isabelle/etc/settings
    - echo 'init_component "'$PWD'/importer-isabelle/target/scala-2.12"' >> /root/.isabelle/etc/settings
    - ./ci-scripts/install-elm.sh
  script:
    - ./sbt -Dprofiles=$profiles clean scalastyle || true
    - ./sbt -Dprofiles=$profiles coverage test
    - ./sbt -Dprofiles=$profiles it:test
    - ./sbt -Dprofiles=$profiles coverageReport coverageOff scapegoat || true
    - ./sbt sonarScan -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
