stages:
  - analyze # linting, testing (with coverage), static code analysis, and upload to sonarqube

build:
  only:
    refs:
      - master
  stage: analyze
  image: openjdk:11-jdk
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "/root/.ivy2/cache"
      - "/root/.sbt"
      - "/root/.m2"
  script:
    - curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
    - gunzip elm.gz
    - chmod +x elm
    - mv elm /usr/local/bin/
    - ./sbt clean
    - ./sbt scalastyle || true
    - ./sbt coverage test coverageReport coverageOff
    - ./sbt scapegoat || true
    - ./sbt sonarScan -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
