stages:
  - analyze # linting, testing (with coverage), static code analysis, and upload to sonarqube

variables:
  profiles: "ui,loader,memory"

build:
  only:
    refs:
      - master
  stage: analyze
  image: openjdk:15-jdk
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "/root/.ivy2/cache"
      - "/root/.sbt"
      - "/root/.m2"
      - "/root/.elm"
  before_script:
    - ./ci-scripts/install-isabelle.sh
    - ./ci-scripts/install-elm.sh
  script:
    - ./sbt -Dprofiles=$profiles clean coverage test
    - ./sbt -Dprofiles=$profiles it:test
    - ./sbt -Dprofiles=$profiles coverageReport coverageOff scapegoat || true
    - ./sbt sonarScan -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
