stages:
  - analyze # linting, testing (with coverage), static code analysis, and upload to sonarqube

variables:
  profiles: "ui,loader"

build:
  only:
    refs:
      - master
  stage: analyze
  image: openjdk:11-jdk
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "/root/.ivy2/cache"
      - "/root/.sbt"
      - "/root/.m2"
  before_script:
    - ./ci-scripts/install-isabelle.sh
    - ./ci-scripts/install-elm.sh
  script:
    - ./sbt clean
    - ./sbt scalastyle || true
    - ./sbt coverage test it:test coverageReport coverageOff
    - ./sbt scapegoat || true
    - ./sbt sonarScan -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
