version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: ./sbt compile test it:test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  dump-isabelle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote
      - run: |
          isabelle/bin/isabelle components -I
          isabelle/bin/isabelle components -a
          isabelle/bin/isabelle jedit -b -l HOL
          isabelle/bin/isabelle dump -a

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - dump-isabelle:
          type: approval
          requires:
            - build
