version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: ./sbt compile test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build