version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.2
    steps:
      - checkout
      - run: ./ci-scripts/install-isabelle.sh
      - run: ./ci-scripts/install-elm.sh
      - restore_cache:
          key: sbt-cache
      - run:
          command: ./sbt -Dprofiles=ui,loader clean compile test it:test
          no_output_timeout: 30min
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "~/.elm"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build