version: 2
jobs:
  build:
    working_directory: ~/isabelle-afp-search
    docker:
      - image: circleci/openjdk:8
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run: |
          curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
          sudo dpkg -i sbt-$SBT_VERSION.deb
          rm sbt-$SBT_VERSION.deb
          sudo apt-get update
          sudo apt-get install -y sbt python-pip git
          pip install awscli
          sudo apt-get clean && sudo apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  dump-isabelle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: |
          isabelle/bin/isabelle components -I
          isabelle/bin/isabelle components -a
          isabelle/bin/isabelle jedit -b -l HOL
          isabelle/bin/isabelle dump -a

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - dump-isabelle:
          type: approval
          requires:
            - build
