version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y npm
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: ./sbt compile test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  dump-isabelle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: git submodule init && git submodule update --remote
      - run: ./scripts/build-isabelle.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - dump-isabelle:
          type: approval
          requires:
            - build
