version: '3'

services:
  solr:
    container_name: prod_solr
    build: .
    restart: always
    environment:
      - SOLR_HEAP=2g
    volumes:
      - ./theorydata:/opt/solr/server/solr/configsets/theorydata:ro
      - data:/var/solr
    command:
      - solr-precreate
      - theorydata
      - /opt/solr/server/solr/configsets/theorydata
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: "{{.Name}}"
    expose:
      - 8983
    ports:
      - 8983:8983
    networks:
      - internal

volumes:
  data:

networks:
  internal: