version: '3'

services:
  solr:
    container_name: prod_solr
    image: solr:8.2.0
    restart: always
    environment:
      - SOLR_HEAP=2g
    volumes:
      - ./configsets:/opt/solr/server/solr/configsets:ro
      - data:/var/solr
    command:
      - solr-precreate
      - theorydata-0.2.0-SNAPSHOT
      - /opt/solr/server/solr/configsets/theorydata-0.2.0-SNAPSHOT
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        tag: "{{.Name}}"
    expose:
      - 8983
    ports:
      - 8983:8983
    networks:
      - internal

volumes:
  data:

networks:
  internal: