version: '3'

services:
  db:
    build: .
    container_name: prod_solr
    restart: always
    environment:
      - SOLR_HEAP=2g
    volumes:
      - data:/var/solr
    ports:
      - 8983:8983
    networks:
      - internal

volumes:
  data:

networks:
  internal: