name: Build
on: 
  push:
    branches:
      - devel
  repository_dispatch:
    branches:
      - devel
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'devel'
      - run: ./sbt -Djdk.util.zip.disableZip64ExtraFieldValidation=true "project importer-isabelle-base" assembly
      - run: |
          git clone --depth 1 https://github.com/isabelle-prover/mirror-isabelle.git isabelle
          isabelle/Admin/init
          echo 'ISABELLE_TOOL_JAVA_OPTIONS="-Xms1600m -Xmx2000m"' >> ~/.isabelle/etc/settings
          echo 'ML_OPTIONS="--minheap 1800M --maxheap 1800M"' >> ~/.isabelle/etc/settings
          isabelle/bin/isabelle components -u importer-isabelle-build
          isabelle/bin/isabelle components -u search-jedit
      - uses: actions/cache@v3
        with:
          path: |
            .sbt
            .ivy2
            ~/.isabelle/contrib
            ~/.isabelle/heaps
          key: ISABELLE_HOME_USER
      - run: |
          export PATH="$PATH:$(pwd)/isabelle/bin"
          ./sbt -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Dprofiles=memory,loader "project findfacts" it:test