name: Build
on: 
  push:
    branches:
      - devel
  repository_dispatch:
    branches:
      - devel
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'devel'
      - run: rm -r isabelle
      - run: git clone --depth 1 https://github.com/isabelle-prover/mirror-isabelle.git isabelle
      - uses: actions/cache@v3
        with:
          path: |
            .sbt
            .ivy2
            .isabelle/contrib
            .isabelle/heaps
          key: ISABELLE_HOME_USER
      - run: ./sbt -Dprofiles=memory,loader "project search-jedit" assembly "project findfacts" it:test